### ISSUE TITLE
Delete node_modules and then, ignore it. 

### ISSUE THREAD

**Issue by michaeljota** [DavidMellul/Opale-Messenger#1]
By general rule, you should not upload dependencies in a repo. Instead, you should use some kind of dependence manager, `npm`, with a dependencies list, `package.json`. 

You should delete `node_modules` and just use `package.json` dependencies instead.

**Comment by DavidMellul** [comment]
Oh alright !
I'm not familiar with this system. 
Thank you for the star and the advice.
EDIT : It's done :)
