### ISSUE TITLE
Tested on Linux Mint Mate

### ISSUE THREAD

**Issue by svein83** [DavidMellul/Opale-Messenger#2]
**It works.**

When cloning the repo with git clone, and using npm to install and  start the app, it works in Linux Mint Mate 18.3.

And it shows up with a notification icon too.

But the bubble background is not transparent, and it is a bit too large for my taste.

**Comment by DavidMellul** [comment]
Thank you for making me aware of it !

Should I update the readme in consequences ?

**Comment by svein83** [comment]
You could mention it. That I got it to work, and that it should work. You
should mention that it hasn't been tested with more than one distro too.
And that you don't use Linux, so you can't support it.

29. jan. 2018 11:55 p.m. skrev "David Mellul" <notifications@github.com>:

Thank you for making me aware of it !

Should I update the readme in consequences ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DavidMellul/Opale-Messenger/issues/2#issuecomment-361415498>,
or mute the thread
